// English source strings keep the catalogue readable.
export const bosnian: Record<string, string> = {
  "This link requires verified access to the same school. Keep it private. Use Check for an answer to refresh it.": "Ovaj link zahtijeva potvrđen pristup istoj školi. Čuvajte ga. Koristite Provjeri odgovor za osvježavanje.",
  "Overview": "Pregled",
  "Anonymous Q&A": "Anonimna pitanja",
  "Class boards": "Razredne ploče",
  "Library Table": "Stol za učenje",
  "Debate Room": "Debatna soba",
  "Noise Monitor": "Mjerač buke",
  "Teacher workspace": "Nastavnički prostor",
  "Teacher space": "Prostor za nastavnike",
  "Student space": "Prostor za učenike",
  "School commons": "Školski prostor",
  "THE SCHOOL COMMONS": "ŠKOLSKI PROSTOR",
  "YOUR WORKSPACE": "VAŠ PROSTOR",
  "Good things happen": "Dobre stvari se dešavaju",
  "when we connect.": "kada se povežemo.",
  "Your school. Your space.": "Tvoja škola. Tvoj prostor.",
  "Switch your perspective": "Promijenite prikaz",
  "Sign out": "Odjava",
  "Tap again to confirm": "Dodirnite ponovo za potvrdu",
  "Leave for the student view?": "Preći na učenički prikaz?",
  "Preview the student view": "Pregled učeničkog prikaza",
  "Built for your school": "Napravljeno za vašu školu",
  "Small tools. A better school day.": "Mali alati. Bolji školski dan.",
  "A space built on trust.": "Prostor zasnovan na povjerenju.",
  "COME ON IN": "DOBRO DOŠLI",
  "A space for everyone.": "Prostor za svakoga.",
  "Are you a student or a teacher?": "Jeste li učenik ili nastavnik?",
  "I’m a student": "Ja sam učenik",
  "I’m a teacher": "Ja sam nastavnik",
  "Preview the student side.": "Pogledajte učenički prikaz.",
  "Ask, connect, and learn together.": "Pitajte, povežite se i učite zajedno.",
  "Listen, guide, and bring class together.": "Slušajte, usmjeravajte i povežite razred.",
  "Students can get started without an account.": "Učenici mogu početi bez računa.",
  "You’re in the teacher workspace. Switch to the student view?": "Nalazite se u nastavničkom prostoru. Preći na učenički prikaz?",
  "Yes, show student view": "Da, prikaži učenički prikaz",
  "Stay here": "Ostani ovdje",
  "A little more connected. A lot more together.": "Malo povezaniji. Mnogo više zajedno.",
  "Main navigation": "Glavna navigacija",
  "SchoolHub home": "Početna stranica SchoolHuba",
  "Switch Student or Teacher": "Promijenite ulogu: učenik ili nastavnik",
  "Close role chooser": "Zatvori izbor uloge",
  "A LITTLE MORE CONNECTED": "MALO POVEZANIJI",
  "Ask the question. Find your people. Make today a little better.": "Postavi pitanje. Pronađi svoje društvo. Uljepšaj današnji dan.",
  "Made for the moments between classes": "Za trenutke između časova",
  "SchoolHub tools": "SchoolHub alati",
  "SPEAK YOUR MIND": "RECI ŠTA MISLIŠ",
  "Big question?": "Veliko pitanje?",
  "Small suggestion?": "Mali prijedlog?",
  "We’re listening.": "Slušamo vas.",
  "A direct line to your teachers and school.": "Direktna veza s nastavnicima i školom.",
  "Always anonymous. Always welcome.": "Uvijek anonimno. Uvijek dobrodošlo.",
  "Ask a question": "Postavi pitanje",
  "just your voice": "samo tvoj glas",
  "No name. No account. No awkwardness.": "Bez imena. Bez računa. Bez nelagode.",
  "LEARN TOGETHER": "UČIMO ZAJEDNO",
  "There’s a seat": "Ima mjesta",
  "at the table.": "za stolom.",
  "Find a study group, share what you know,": "Pronađi grupu za učenje, podijeli znanje,",
  "or start something of your own.": "ili pokreni nešto svoje.",
  "Find your study group": "Pronađi grupu za učenje",
  "Better together, one session at a time.": "Bolje je zajedno, termin po termin.",
  "A DIFFERENT PERSPECTIVE": "DRUGAČIJA PERSPEKTIVA",
  "Different sides.": "Različiti stavovi.",
  "One conversation.": "Jedan razgovor.",
  "ROOM TO FOCUS": "PROSTOR ZA FOKUS",
  "A little quieter.": "Malo tiše.",
  "A gentle nudge toward a calmer classroom.": "Blagi podsjetnik za mirniju učionicu.",
  "At the table today": "Danas za stolom",
  "See the board": "Pogledaj ploču",
  "The next great study session starts with you.": "Sljedeći odličan termin učenja počinje s tobom.",
  "Pull up a chair. Invite someone to learn together.": "Pridruži se. Pozovi nekoga da učite zajedno.",
  "Start a session": "Pokreni termin",
  "FROM THE COMMONS": "IZ ŠKOLSKOG PROSTORA",
  "Every voice": "Svaki glas",
  "makes a difference.": "pravi razliku.",
  "See what your teachers have shared with the school community.": "Pogledajte šta su nastavnici podijelili sa školskom zajednicom.",
  "A thoughtful question can start a conversation that changes someone’s day.": "Promišljeno pitanje može pokrenuti razgovor koji nekome uljepša dan.",
  "Browse class boards": "Pregledaj razredne ploče",
  "Share what’s on your mind": "Podijeli šta ti je na umu",
  "You choose whether your question is public or private.": "Vi birate je li pitanje javno ili privatno.",
  "THE OPEN SCHOOL BACKCHANNEL": "OTVORENI ŠKOLSKI KANAL",
  "What’s on your mind?": "Šta ti je na umu?",
  "A question, an idea, or something we could do better. Your voice belongs here.": "Pitanje, ideja ili nešto što možemo poboljšati. Ovdje je mjesto za tvoj glas.",
  "Your voice has been heard.": "Tvoj glas se čuo.",
  "Your message is in the right inbox. Save the private receipt below to read your teacher’s answer.": "Poruka je u pravom pretincu. Sačuvajte privatnu potvrdu ispod da biste pročitali odgovor nastavnika.",
  "Anyone with this receipt can read your question and reply. We cannot recover it if you lose it.": "Svako ko ima ovu potvrdu može pročitati pitanje i odgovor. Ne možemo je vratiti ako je izgubite.",
  "Copy receipt link": "Kopiraj link potvrde",
  "Read my answer": "Pročitaj moj odgovor",
  "Ask another question": "Postavi drugo pitanje",
  "One question. A direct connection.": "Jedno pitanje. Direktna veza.",
  "Choose where your message goes. We’ll take it from there.": "Odaberite kome šaljete poruku. Mi ćemo se pobrinuti za ostalo.",
  "Who would you like to reach?": "Kome se želite obratiti?",
  "Specific teacher": "Određeni nastavnik",
  "Department": "Odsjek",
  "School life": "Školski život",
  "Choose a teacher": "Odaberite nastavnika",
  "Choose a department": "Odaberite odsjek",
  "Loading the school directory…": "Učitavanje školskog imenika…",
  "Select a recipient": "Odaberite primaoca",
  "Your school hasn’t added its teachers yet. You can still write to a department or school life.": "Škola još nije dodala nastavnike. I dalje možete pisati odsjeku ili za školski život.",
  "Your question or suggestion": "Vaše pitanje ili prijedlog",
  "I’ve been wondering…": "Zanima me…",
  "A little kindness goes a long way.": "Malo ljubaznosti mnogo znači.",
  "Who can see your question?": "Ko može vidjeti vaše pitanje?",
  "Private": "Privatno",
  "Public": "Javno",
  "Only authorized staff and anyone holding your receipt link. Teachers cannot publish it.": "Samo ovlašteno osoblje i osobe koje imaju link potvrde. Nastavnici ga ne mogu objaviti.",
  "Other students can see your anonymous question and the teacher’s answer.": "Drugi učenici mogu vidjeti vaše anonimno pitanje i odgovor nastavnika.",
  "Leave this empty": "Ostavite prazno",
  "No name, email, or account attached.": "Bez povezanog imena, emaila ili računa.",
  "Submit anonymously": "Pošalji anonimno",
  "Just your voice.": "Samo tvoj glas.",
  "Nothing attached.": "Bez ličnih podataka.",
  "Sometimes the best questions are the ones you’re a little hesitant to ask out loud.": "Ponekad su najbolja pitanja ona koja se ustručavamo izgovoriti naglas.",
  "Find the right inbox": "Pronađi pravi pretinac",
  "A teacher, a department, or the wider school.": "Nastavnik, odsjek ili cijela škola.",
  "Say what’s on your mind": "Reci šta ti je na umu",
  "Keep it thoughtful and under 280 characters.": "Neka bude promišljeno i kraće od 280 znakova.",
  "Let the conversation begin": "Neka razgovor počne",
  "Save your receipt to read the reply. Public questions can also appear on class boards.": "Sačuvajte potvrdu za čitanje odgovora. Javna pitanja mogu se pojaviti i na razrednim pločama.",
  "You choose public or private. Both are anonymous. Please leave personal details out of your question.": "Birate javno ili privatno. Oboje je anonimno. Ne navodite lične podatke u pitanju.",
  "Browse public questions": "Pregledaj javna pitanja",
  "Public questions": "Javna pitanja",
  "Anonymous voices": "Anonimni glasovi",
  "Questions shared publicly by students. Approved questions and their answers appear here.": "Pitanja koja su učenici javno podijelili. Ovdje se prikazuju odobrena pitanja i odgovori.",
  "Answered": "Odgovoreno",
  "Awaiting an answer": "Čeka odgovor",
  "Teacher’s answer": "Odgovor nastavnika",
  "No public questions yet. You can start the conversation.": "Još nema javnih pitanja. Vi možete pokrenuti razgovor.",
  "Public question": "Javno pitanje",
  "Private question": "Privatno pitanje",
  "YOUR PRIVATE RECEIPT": "VAŠA PRIVATNA POTVRDA",
  "Your question, and its answer.": "Vaše pitanje i odgovor.",
  "Keep this link private. It gives access to this question without an account.": "Čuvajte ovaj link. Omogućava pristup pitanju bez računa.",
  "This question has been archived.": "Ovo pitanje je arhivirano.",
  "Your teacher has not answered yet. Check this receipt again later.": "Nastavnik još nije odgovorio. Provjerite ovu potvrdu kasnije.",
  "Check for an answer": "Provjeri odgovor",
  "PUBLIC CLASS BOARDS": "JAVNE RAZREDNE PLOČE",
  "Shared with your class.": "Podijeljeno s vašim razredom.",
  "Find your teacher’s board. Only questions your teacher chooses to pin appear here. No student login needed.": "Pronađite ploču nastavnika. Ovdje su pitanja koja je nastavnik prikvačio. Prijava učenika nije potrebna.",
  "Find a class board": "Pronađite razrednu ploču",
  "Search by class or board title": "Pretražite po razredu ili nazivu ploče",
  "Finding your class boards…": "Traženje razrednih ploča…",
  "No matching boards.": "Nema odgovarajućih ploča.",
  "Your class boards will appear here.": "Ovdje će se pojaviti razredne ploče.",
  "Try another class or board name.": "Pokušajte s drugim razredom ili nazivom.",
  "Your teacher can create a board and pin questions from their inbox.": "Nastavnik može kreirati ploču i prikvačiti javna pitanja iz pretinca.",
  "View questions shared by your teacher": "Pogledajte pitanja koja je nastavnik podijelio",
  "All class boards": "Sve razredne ploče",
  "THE PUBLIC CLASS BOARD": "JAVNA RAZREDNA PLOČA",
  "Shared with the class.": "Podijeljeno s razredom.",
  "Thoughtful questions, chosen by your teacher. A conversation for everyone.": "Promišljena pitanja koja je odabrao nastavnik. Razgovor za sve.",
  "Shared by your teacher": "Podijelio nastavnik",
  "A conversation is on its way.": "Razgovor uskoro počinje.",
  "Your teacher’s published questions will appear here.": "Ovdje će se pojaviti objavljena pitanja nastavnika.",
  "THE LIBRARY TABLE": "STOL ZA UČENJE",
  "Better when we learn together.": "Bolje je kada učimo zajedno.",
  "Find a session, pull up a chair, and figure it out together.": "Pronađi termin, pridruži se i učite zajedno.",
  "GRADE": "RAZRED",
  "SUBJECT": "PREDMET",
  "MEETING PLACE": "MJESTO SASTANKA",
  "DATE": "DATUM",
  "Every grade": "Svi razredi",
  "Every subject": "Svi predmeti",
  "Search meeting places": "Pretražite mjesta sastanka",
  "Finding a seat at the table…": "Traženje mjesta za stolom…",
  "No sessions match just yet.": "Još nema odgovarajućih termina.",
  "The table is yours to start.": "Vi možete započeti učenje.",
  "Try another filter, or start a session of your own.": "Pokušajte s drugim filterom ili pokrenite svoj termin.",
  "Clear filters": "Očisti filtere",
  "Choose a subject, a time, and a place. Someone else might be looking for exactly the same thing.": "Odaberite predmet, vrijeme i mjesto. Možda još neko traži upravo to.",
  "Start the first session": "Pokreni prvi termin",
  "Happening now": "U toku",
  "Today": "Danas",
  "A fellow student": "Drugi učenik",
  "Everyone welcome": "Svi su dobrodošli",
  "Say hello:": "Javite se:",
  "Open spots are updated by the host. Just show up or get in touch.": "Organizator ažurira slobodna mjesta. Dođite ili se javite.",
  "Sessions leave the board when they end. Times:": "Termini nestaju s ploče kada završe. Vremenska zona:",
  "on the board": "na ploči",
  "session": "termin",
  "sessions": "termina",
  "spot": "mjesto",
  "spots": "mjesta",
  "open": "slobodno",
  "All": "Svi",
  "National": "Nacionalni",
  "Grade I": "I razred",
  "Grade II": "II razred",
  "Grade III": "III razred",
  "Grade IV": "IV razred",
  "PULL UP A CHAIR": "PRIDRUŽITE SE",
  "Start something together.": "Pokrenite nešto zajedno.",
  "Share what you’re studying. Find someone to study with.": "Podijelite šta učite. Pronađite društvo za učenje.",
  "YOUR PRIVATE MANAGEMENT LINK": "VAŠ PRIVATNI LINK ZA UPRAVLJANJE",
  "Plans can change.": "Planovi se mogu promijeniti.",
  "Keep your session up to date, or take it off the board.": "Ažurirajte termin ili ga uklonite s ploče.",
  "Opening your private management link…": "Otvaranje privatnog linka za upravljanje…",
  "Session cancelled.": "Termin je otkazan.",
  "Your session has been removed from the board.": "Vaš termin je uklonjen s ploče.",
  "Back to the table": "Nazad na stol za učenje",
  "This private management link is unavailable.": "Privatni link za upravljanje nije dostupan.",
  "There’s a new seat at the table.": "Novo mjesto za stolom.",
  "Your session is on the board. Keep your private management link to edit or cancel it later.": "Termin je objavljen. Sačuvajte privatni link za naknadne izmjene ili otkazivanje.",
  "Copy private link": "Kopiraj privatni link",
  "Link copied": "Link je kopiran",
  "Copy the private link above manually.": "Ručno kopirajte privatni link iznad.",
  "See your session": "Pogledaj svoj termin",
  "Anyone with this private link can manage your session. Save it somewhere safe.": "Svako ko ima privatni link može upravljati terminom. Sačuvajte ga na sigurnom mjestu.",
  "Your session, your details.": "Vaš termin, vaši detalji.",
  "Make room for a little teamwork.": "Napravite mjesta za zajednički rad.",
  "A few details help the right people find you.": "Nekoliko detalja pomaže pravim ljudima da vas pronađu.",
  "Your session has been updated.": "Termin je ažuriran.",
  "Grade": "Razred",
  "Programme": "Program",
  "Subject": "Predmet",
  "Loading subjects…": "Učitavanje predmeta…",
  "Choose a subject": "Odaberite predmet",
  "What are you working on?": "Na čemu radite?",
  "e.g. Kinematics & vectors, or Criterion A essay prep": "npr. Kinematika i vektori ili priprema eseja",
  "Meeting place": "Mjesto sastanka",
  "e.g. Library, upstairs table or Room 102": "npr. biblioteka, stol na spratu ili učionica 102",
  "Date": "Datum",
  "Meeting starts at": "Početak sastanka",
  "Meeting ends at": "Završetak sastanka",
  "Choose an hour": "Odaberite sat",
  "Choose a start and end hour in": "Odaberite početni i završni sat u zoni",
  ". Times are available every 15 minutes.": ". Dostupni su intervali od 15 minuta.",
  "Open spots": "Slobodna mjesta",
  "Open to anyone": "Otvoreno za sve",
  "A few seats available": "Ograničen broj mjesta",
  "How many spots?": "Koliko mjesta?",
  "Your first name": "Vaše ime",
  "optional": "neobavezno",
  "What should people call you?": "Kako da vas oslovljavaju?",
  "Contact handle": "Kontakt",
  "Instagram / WhatsApp handle": "Instagram / WhatsApp kontakt",
  "This will be visible on the public board.": "Ovo će biti vidljivo na javnoj ploči.",
  "Learning is better with company.": "Učenje je bolje u društvu.",
  "Save changes": "Sačuvaj izmjene",
  "Post your session": "Objavi termin",
  "Cancel this session": "Otkaži termin",
  "Back to board": "Nazad na ploču",
  "One table.": "Jedan stol.",
  "Plenty of possibilities.": "Mnogo mogućnosti.",
  "Revision partners, a tricky problem set, or just some company while you work. It all belongs here.": "Društvo za ponavljanje, teški zadaci ili samo zajednički rad. Sve je dobrodošlo.",
  "Be specific": "Budite precizni",
  "A clear topic helps people know what to expect.": "Jasna tema pomaže drugima da znaju šta ih očekuje.",
  "Make it easy to find you": "Olakšajte drugima da vas pronađu",
  "Pick a shared school space and a realistic time.": "Odaberite zajednički školski prostor i odgovarajuće vrijeme.",
  "Your session leaves the active board when its end time passes. Keep your private link if plans change.": "Termin nestaje s aktivne ploče po završetku. Sačuvajte privatni link ako se planovi promijene.",
  "Type where you’ll meet.": "Unesite gdje ćete se sastati.",
  "THE DEBATE ROOM": "DEBATNA SOBA",
  "A different point of view.": "Drugačija tačka gledišta.",
  "Join your classroom debate. Find your side. Bring your voice.": "Pridruži se razrednoj debati. Pronađi svoj stav. Reci svoje mišljenje.",
  "Your class is waiting.": "Razred vas čeka.",
  "Scan the QR on your teacher’s screen, or enter the six-character room code.": "Skenirajte QR kod na ekranu nastavnika ili unesite kod sobe od šest znakova.",
  "Room code": "Kod sobe",
  "Six-character room code": "Kod sobe od šest znakova",
  "Join": "Pridruži se",
  "Scan QR code": "Skeniraj QR kod",
  "No account needed. Just a name your teacher will recognize.": "Račun nije potreban. Samo ime koje će nastavnik prepoznati.",
  "Bring a room": "Povežite sobu",
  "full of ideas together.": "punu ideja.",
  "Teachers set the prompt and stances. SchoolHub takes care of the lobby, fair assignments, and prep timer.": "Nastavnici zadaju temu i stavove. SchoolHub upravlja čekaonicom, ravnomjernim rasporedom i vremenom pripreme.",
  "Speaking and debating happen in person. The phones just help everyone get into place.": "Razgovor i debata odvijaju se uživo. Telefoni samo pomažu pri raspoređivanju.",
  "Join the room": "Pridružite se sobi",
  "Scan the QR or enter your teacher’s code. Your phone becomes your place in the lobby.": "Skenirajte QR ili unesite nastavnikov kod. Telefon čuva vaše mjesto u čekaonici.",
  "Meet your perspective": "Upoznajte svoj stav",
  "The teacher shuffles the class into balanced sides. Your assigned stance appears on your phone.": "Nastavnik nasumično raspoređuje razred u ravnomjerne grupe. Dodijeljeni stav se prikazuje na telefonu.",
  "Make your case": "Iznesite argumente",
  "Prepare together while the timer runs. Then put the phones down and start the conversation.": "Pripremajte se zajedno dok vrijeme teče. Zatim odložite telefone i započnite razgovor.",
  "Finding your classroom…": "Traženje učionice…",
  "Join a classroom debate. Bring your voice.": "Pridružite se razrednoj debati. Iznesite svoje mišljenje.",
  "Let’s find your room.": "Pronađimo vašu sobu.",
  "Check your room code": "Provjerite kod sobe",
  "That’s a wrap.": "Debata je završena.",
  "This debate has ended. Thanks for bringing your voice.": "Debata je završena. Hvala na učešću.",
  "DEBATE CLOSED": "DEBATA JE ZATVORENA",
  "The sides are already set.": "Stavovi su već dodijeljeni.",
  "Ask your teacher to reopen the lobby if you need to join.": "Zamolite nastavnika da ponovo otvori čekaonicu ako se želite pridružiti.",
  "Join a different room": "Pridruži se drugoj sobi",
  "You’re in,": "Pridružili ste se,",
  ", YOUR PERSPECTIVE IS": ", VAŠ STAV JE",
  "Your stance is set. Find your group and make your case.": "Stav je dodijeljen. Pronađite grupu i pripremite argumente.",
  "Waiting for the shuffle…": "Čekanje rasporeda…",
  "Your teacher will assign your stance when the class is ready.": "Nastavnik će dodijeliti stavove kada razred bude spreman.",
  "Your place stays with this browser if you refresh.": "Vaše mjesto ostaje sačuvano u ovom pregledniku nakon osvježavanja.",
  "Let’s take a side.": "Odaberimo perspektivu.",
  "Enter a name your teacher will recognize. We’ll save your place in this browser.": "Unesite ime koje će nastavnik prepoznati. Sačuvat ćemo vaše mjesto u ovom pregledniku.",
  "Your name": "Vaše ime",
  "First name + initial, if needed": "Ime i inicijal, po potrebi",
  "No email. No account. Just this debate.": "Bez emaila. Bez računa. Samo ova debata.",
  "Students join on their phones. The conversation happens in the room.": "Učenici se pridružuju telefonom. Razgovor se odvija uživo.",
  "CLASSROOM DEBATE ·": "RAZREDNA DEBATA ·",
  "One click assigns everyone a stance.": "Jedan klik dodjeljuje stav svima.",
  "One shuffle. Balanced sides.": "Jedan raspored. Ravnomjerne grupe.",
  "PREPARATION TIME": "VRIJEME ZA PRIPREMU",
  "PREPARATION REMAINING": "PREOSTALO VRIJEME PRIPREME",
  "WAITING FOR YOUR TEACHER TO START": "ČEKANJE DA NASTAVNIK POKRENE",
  "Take a moment to prepare": "Pripremite se",
  "Start the timer, then let the real conversation begin.": "Pokrenite vrijeme, pa započnite pravi razgovor.",
  "Back to SchoolHub": "Nazad na SchoolHub",
  "Or enter your room code": "Ili unesite kod sobe",
  "Camera preview for QR scanning": "Pregled kamere za QR skeniranje",
  "Point your camera at the QR on your teacher’s screen.": "Usmjerite kameru prema QR kodu na ekranu nastavnika.",
  "Enter code instead": "Umjesto toga unesite kod",
  "That QR isn’t a debate room. Point at your teacher’s code.": "Ovaj QR nije kod debate. Usmjerite kameru prema nastavnikovom kodu.",
  "Camera preview or QR scanner could not start. Try again, or enter the room code instead.": "Kamera ili QR skener se nisu pokrenuli. Pokušajte ponovo ili unesite kod sobe.",
  "Camera permission wasn’t granted. Tap Try again and choose Allow when your browser asks.": "Pristup kameri nije odobren. Pritisnite Pokušaj ponovo i odaberite Dozvoli kada preglednik zatraži.",
  "No camera was found on this device. Enter the room code instead.": "Kamera nije pronađena na uređaju. Unesite kod sobe.",
  "The camera could not start. Close other apps using it, then try again.": "Kamera se nije pokrenula. Zatvorite druge aplikacije koje je koriste i pokušajte ponovo.",
  "This page’s security policy blocks the camera. Reload after your school’s site has been updated.": "Sigurnosne postavke stranice blokiraju kameru. Osvježite nakon ažuriranja školske stranice.",
  "This browser can’t open the camera here. Use your school’s https address in Chrome (or your phone’s camera app) — or enter the room code instead.": "Preglednik ovdje ne može otvoriti kameru. Koristite školsku HTTPS adresu u Chromeu ili aplikaciju kamere, ili unesite kod sobe.",
  "The camera only works over a secure connection. Open your school’s https address on your phone (not a plain http or local-network preview link) and try again.": "Kamera radi samo preko sigurne veze. Otvorite školsku HTTPS adresu na telefonu i pokušajte ponovo.",
  "Camera is blocked. In Chrome: tune icon by the address bar → Permissions → Camera → Allow. If Camera isn’t listed: ⋮ → Settings → Site settings → Camera → on. Still nothing? Open Android Settings → Apps → Chrome → Permissions → Camera → Allow. Then tap Try again.": "Kamera je blokirana. U Chromeu: ikona pored adrese → Dozvole → Kamera → Dozvoli. Ako kamera nije navedena: ⋮ → Postavke → Postavke web-lokacije → Kamera → uključi. Provjerite i Android postavke → Aplikacije → Chrome → Dozvole → Kamera → Dozvoli. Zatim pokušajte ponovo.",
  "THE CLASSROOM NOISE MONITOR": "RAZREDNI MJERAČ BUKE",
  "Make space for focus.": "Napravite prostor za fokus.",
  "A gentle visual reminder. A calmer room for everyone.": "Blagi vizuelni podsjetnik. Mirniji prostor za sve.",
  "Open noise monitor in fullscreen": "Otvori mjerač buke preko cijelog ekrana",
  "LISTENING TO YOUR ROOM": "OSLUŠKIVANJE PROSTORIJE",
  "A QUIETER CLASSROOM STARTS HERE": "TIŠA UČIONICA POČINJE OVDJE",
  "RELATIVE NOISE LEVEL": "RELATIVNI NIVO BUKE",
  "A little room to focus.": "Malo prostora za fokus.",
  "Listening to the quiet…": "Osluškivanje tišine…",
  "Let’s bring it down a little.": "Smanjimo buku malo.",
  "A little softer, please.": "Malo tiše, molimo.",
  "Just the right kind of quiet.": "Upravo prava tišina.",
  "Keep the room quiet for three seconds. We’ll use this as your starting point.": "Neka prostorija bude tiha tri sekunde. To ćemo koristiti kao početnu vrijednost.",
  "The gauge follows the sound in your room. Green is calm, yellow is rising, and red is a reminder to reset.": "Mjerač prati zvuk u prostoriji. Zeleno je mirno, žuto znači porast, a crveno je podsjetnik da se stiša.",
  "Start the microphone, put this on the board, and let the room find its rhythm.": "Pokrenite mikrofon, prikažite mjerač na ploči i pustite prostoriju da pronađe ritam.",
  "Stop listening": "Zaustavi osluškivanje",
  "Opening microphone…": "Otvaranje mikrofona…",
  "Start noise monitor": "Pokreni mjerač buke",
  "Calm & focused": "Mirno i fokusirano",
  "Getting louder": "Sve glasnije",
  "Time to reset": "Vrijeme da se stiša",
  "Sensitivity": "Osjetljivost",
  "Calibrate a quiet room": "Kalibriraj tihu prostoriju",
  "Audio stays in this browser. Nothing is recorded, uploaded, or stored.": "Zvuk ostaje u pregledniku. Ništa se ne snima, ne šalje niti pohranjuje.",
  "This is a relative classroom indicator, not a calibrated decibel meter.": "Ovo je relativni razredni pokazatelj, a ne kalibrirani mjerač decibela.",
  "Fullscreen is unavailable in this browser.": "Prikaz preko cijelog ekrana nije dostupan u ovom pregledniku.",
  "Microphone access needs HTTPS or localhost and a supported browser.": "Pristup mikrofonu zahtijeva HTTPS ili localhost i podržan preglednik.",
  "Microphone permission was declined. Allow microphone access in your browser, then try again.": "Dozvola za mikrofon je odbijena. Dozvolite pristup u pregledniku pa pokušajte ponovo.",
  "No microphone was found. Connect one and try again.": "Mikrofon nije pronađen. Povežite ga i pokušajte ponovo.",
  "The microphone was disconnected. Reconnect it and start again.": "Mikrofon je isključen. Povežite ga i pokrenite ponovo.",
  "TEACHER WORKSPACE": "NASTAVNIČKI PROSTOR",
  "YOUR TEACHER WORKSPACE": "VAŠ NASTAVNIČKI PROSTOR",
  "A place to listen.": "Mjesto za slušanje.",
  "Your private inbox and classroom tools, all together.": "Vaš privatni pretinac i razredni alati na jednom mjestu.",
  "Opening your teacher workspace…": "Otvaranje nastavničkog prostora…",
  "A small space to listen. A few tools to bring your class together.": "Mali prostor za slušanje. Nekoliko alata za povezivanje razreda.",
  "School settings": "Školske postavke",
  "New debate": "Nova debata",
  "WAITING TO BE HEARD": "ČEKA DA BUDE SASLUŠANO",
  "OPEN CLASSROOM DEBATES": "OTVORENE RAZREDNE DEBATE",
  "YOUR PUBLIC BOARDS": "VAŠE JAVNE PLOČE",
  "Your inbox": "Vaš pretinac",
  "Workspace views": "Prikazi prostora",
  "Destination": "Odredište",
  "All your inboxes": "Svi vaši pretinci",
  "Sent to you": "Poslano vama",
  "Your departments": "Vaši odsjeci",
  "Question status": "Status pitanja",
  "New questions": "Nova pitanja",
  "Archived": "Arhivirano",
  "All statuses": "Svi statusi",
  "Needs review": "Potreban pregled",
  "Teacher inbox": "Nastavnički pretinac",
  "Write an answer": "Napišite odgovor",
  "Edit your answer": "Uredite odgovor",
  "Save answer": "Sačuvaj odgovor",
  "Your answer is visible to everyone with this public question.": "Vaš odgovor je vidljiv svima uz ovo javno pitanje.",
  "Only the student with the private receipt and authorized staff can read this answer.": "Samo učenik s privatnom potvrdom i ovlašteno osoblje mogu pročitati odgovor.",
  "Answer saved. The student can read it using their receipt link.": "Odgovor je sačuvan. Učenik ga može pročitati putem linka potvrde.",
  "Approve text": "Odobri tekst",
  "Pin to board": "Prikvači na ploču",
  "Unpin": "Otkači",
  "Archive": "Arhiviraj",
  "Restore": "Vrati",
  "A little breathing room.": "Malo prostora za predah.",
  "No questions in this view. New messages will appear automatically.": "Nema pitanja u ovom prikazu. Nove poruke pojavit će se automatski.",
  "Your classroom conversations": "Vaši razredni razgovori",
  "Room": "Soba",
  "Waiting for students": "Čekanje učenika",
  "Stances assigned": "Stavovi su dodijeljeni",
  "Ended": "Završeno",
  "Start a good conversation.": "Pokrenite dobar razgovor.",
  "Set a prompt and perspectives. Let SchoolHub handle the fair shuffle.": "Zadajte temu i stavove. SchoolHub će napraviti ravnomjeran raspored.",
  "Create your first debate": "Kreirajte prvu debatu",
  "There’s a question waiting to happen.": "Neko pitanje čeka da bude postavljeno.",
  "Your private inbox includes messages sent directly to you and to your assigned departments.": "Vaš pretinac sadrži poruke upućene vama i vašim odsjecima.",
  "Open your inbox": "Otvori pretinac",
  "YOUR CLASS BOARDS": "VAŠE RAZREDNE PLOČE",
  "Share the conversation.": "Podijelite razgovor.",
  "Pin public questions from your inbox to share them. Private questions cannot be pinned. Students can find every board under Class boards. Use Edit board to rename it, remove questions, or copy its student link.": "Prikvačite javna pitanja iz pretinca. Privatna pitanja se ne mogu prikvačiti. Učenici pronalaze ploče pod Razredne ploče. Opcija Uredi ploču omogućava preimenovanje, uklanjanje pitanja i kopiranje učeničkog linka.",
  "Board for pin / unpin actions": "Ploča za prikvačivanje ili uklanjanje",
  "Edit board": "Uredi ploču",
  "Student view": "Učenički prikaz",
  "Create a public board": "Kreirajte javnu ploču",
  "New board title": "Naziv nove ploče",
  "e.g. IB Physics commons": "npr. IB fizika",
  "New board URL slug": "URL oznaka nove ploče",
  "Create board": "Kreiraj ploču",
  "Published questions are visible to anyone with the board link.": "Objavljena pitanja vidljiva su svima koji imaju link ploče.",
  "Open the classroom noise monitor": "Otvori razredni mjerač buke",
  "Question shared on your selected public board.": "Pitanje je podijeljeno na odabranoj javnoj ploči.",
  "Question removed from your selected public board.": "Pitanje je uklonjeno s odabrane javne ploče.",
  "Question updated.": "Pitanje je ažurirano.",
  "Board created. Open your inbox, select this board, and pin a question to publish it.": "Ploča je kreirana. Otvorite pretinac, odaberite ploču i prikvačite javno pitanje za objavu.",
  "Opening your class board…": "Otvaranje razredne ploče…",
  "EDIT YOUR CLASS BOARD": "UREDI RAZREDNU PLOČU",
  "Your class board.": "Vaša razredna ploča.",
  "Rename your board, share its student link, and manage the questions you have pinned.": "Preimenujte ploču, podijelite učenički link i upravljajte prikvačenim pitanjima.",
  "Board title": "Naziv ploče",
  "Save board title": "Sačuvaj naziv ploče",
  "Board title saved. Your student link stays the same.": "Naziv je sačuvan. Učenički link ostaje isti.",
  "Students can find this board under Class boards or open its link directly.": "Učenici mogu pronaći ploču pod Razredne ploče ili otvoriti link direktno.",
  "View student board": "Pogledaj učeničku ploču",
  "Copy student link": "Kopiraj učenički link",
  "Pin questions from your inbox": "Prikvači pitanja iz pretinca",
  "Pinned questions": "Prikvačena pitanja",
  "Removing…": "Uklanjanje…",
  "Remove from board": "Ukloni s ploče",
  "Choose what your class sees.": "Odaberite šta razred vidi.",
  "Open your inbox, select this board, and pin a question to publish it.": "Otvorite pretinac, odaberite ploču i prikvačite javno pitanje za objavu.",
  "Question removed from this board. It remains in your inbox.": "Pitanje je uklonjeno s ploče. Ostaje u vašem pretincu.",
  "Open the student board and copy its address from your browser.": "Otvorite učeničku ploču i kopirajte adresu iz preglednika.",
  "CLASSROOM CONVERSATIONS": "RAZREDNI RAZGOVORI",
  "One prompt. Many perspectives.": "Jedna tema. Mnogo perspektiva.",
  "A prompt, a few perspectives, and a fair place for everyone.": "Tema, nekoliko stavova i ravnopravno mjesto za svakoga.",
  "Let’s open up the room.": "Otvorimo sobu.",
  "Debate prompt": "Tema debate",
  "e.g. Should schools replace exams with project-based assessment?": "npr. Trebaju li škole zamijeniti ispite projektnim ocjenjivanjem?",
  "Stances": "Stavovi",
  "Add a stance": "Dodaj stav",
  "For the motion": "Za prijedlog",
  "Against the motion": "Protiv prijedloga",
  "Preparation time": "Vrijeme pripreme",
  "Open the lobby": "Otvori čekaonicu",
  "Everyone gets a place in the conversation.": "Svako dobija mjesto u razgovoru.",
  "Meet your perspectives.": "Upoznajte svoje stavove.",
  "Let a fair shuffle introduce a new perspective. Groups are balanced automatically, with at most one student difference.": "Nasumičan raspored donosi novu perspektivu. Grupe se automatski izjednačavaju uz razliku od najviše jednog učenika.",
  "Students scan, enter their names, and join.": "Učenici skeniraju kod, unose ime i pridružuju se.",
  "2–4 sides": "2–4 strane",
  "Opening the classroom…": "Otvaranje učionice…",
  "LIVE CLASSROOM DEBATE": "RAZREDNA DEBATA UŽIVO",
  "A shared conversation.": "Zajednički razgovor.",
  "Put the QR on the board. Let the room fill up.": "Prikažite QR na ploči i pustite učenike da se pridruže.",
  "Projector view": "Prikaz za projektor",
  "Open student view": "Otvori učenički prikaz",
  "Enlarge across the screen": "Proširi preko ekrana",
  "Put the QR on the board": "Prikaži QR na ploči",
  "Enlarge QR": "Povećaj QR",
  "Copy join link": "Kopiraj link za pridruživanje",
  "Copied": "Kopirano",
  "Copy the room link below manually.": "Ručno kopirajte link sobe ispod.",
  "Point your phone camera at the code — it opens the room and joins automatically.": "Usmjerite kameru telefona prema kodu — otvara sobu i automatski se pridružuje.",
  "Shuffle the room": "Rasporedi učesnike",
  "Assign stances": "Dodijeli stavove",
  "The waiting room": "Čekaonica",
  "Your students will appear here as they join. Let them scan the QR or enter the code.": "Učenici će se prikazati kako se pridružuju. Neka skeniraju QR ili unesu kod.",
  "STUDENTS": "UČENICI",
  "PERSPECTIVE": "STAV",
  "Everyone has a place.": "Svako ima svoje mjesto.",
  "Stances are set. Give your students a moment to prepare.": "Stavovi su dodijeljeni. Dajte učenicima vremena za pripremu.",
  "Assign stances to start the timer.": "Dodijelite stavove za pokretanje vremena.",
  "Start": "Pokreni",
  "Pause": "Pauziraj",
  "Reset preparation timer": "Resetuj vrijeme pripreme",
  "Reopen lobby & clear assignments": "Ponovo otvori čekaonicu i obriši raspored",
  "End debate": "Završi debatu",
  "This clears every assignment and allows new students to join. Ready to reopen?": "Ovo briše raspored i omogućava novim učenicima da se pridruže. Ponovo otvoriti?",
  "This closes the debate for everyone. Ready to end?": "Ovo završava debatu za sve. Završiti?",
  "Keep current session": "Zadrži trenutnu sesiju",
  "Yes,": "Da,",
  "end debate": "završi debatu",
  "Lobbies close to new arrivals after assignment. Reopening clears the assignments so you can shuffle everyone again.": "Nakon dodjele stavova nema novih pridruživanja. Ponovno otvaranje briše raspored radi nove dodjele.",
  "A conversation well had.": "Dobar razgovor je završen.",
  "This debate is closed. Start a new conversation whenever you’re ready.": "Debata je zatvorena. Pokrenite novi razgovor kada budete spremni.",
  "The room is open.": "Soba je otvorena.",
  "SCHOOL ADMINISTRATION": "ŠKOLSKA ADMINISTRACIJA",
  "Make this space yours.": "Prilagodite prostor svojoj školi.",
  "Invite your teachers, connect their inboxes, and shape your school directory.": "Pozovite nastavnike, povežite pretince i uredite školski imenik.",
  "Opening school settings…": "Otvaranje školskih postavki…",
  "Your teachers": "Vaši nastavnici",
  "Start with your team.": "Počnite sa svojim timom.",
  "Invite a teacher to connect your school.": "Pozovite nastavnika da povežete školu.",
  "Invite a teacher.": "Pozovite nastavnika.",
  "They’ll receive an email with a link to sign in.": "Primit će email s linkom za prijavu.",
  "Display name": "Prikazano ime",
  "e.g. Ms. Kowalska": "npr. nastavnica Hadžić",
  "School email": "Školski email",
  "Send teacher invitation": "Pošalji poziv nastavniku",
  "Add to your directory.": "Dodajte u imenik.",
  "Make the subjects and spaces match your school.": "Prilagodite predmete i prostore svojoj školi.",
  "Type": "Vrsta",
  "Location": "Lokacija",
  "Name": "Naziv",
  "Name of subject, department, or space": "Naziv predmeta, odsjeka ili prostora",
  "Add to directory": "Dodaj u imenik",
  "Questions needing review": "Pitanja za pregled",
  "flagged": "označeno",
  "No flagged questions waiting for review.": "Nema označenih pitanja za pregled.",
  "Recent staff actions": "Nedavne radnje osoblja",
  "Staff": "Osoblje",
  "staff": "članova osoblja",
  "Receive general / school life messages": "Primaj opće poruke i poruke o školskom životu",
  "Department inboxes": "Pretinci odsjeka",
  "Saving…": "Spremanje…",
  "Access saved": "Pristup sačuvan",
  "Save inbox access": "Sačuvaj pristup pretincima",
  "Teacher invited. Set their department inboxes below.": "Nastavnik je pozvan. Dodijelite mu pretince odsjeka ispod.",
  "School directory updated.": "Školski imenik je ažuriran.",
  "A little closer to your class.": "Malo bliže svom razredu.",
  "Sign in with your invited school email to open your inbox and classroom tools.": "Prijavite se pozvanim školskim emailom za pristup pretincu i razrednim alatima.",
  "Email sign-in code": "Kod za prijavu iz emaila",
  "Enter your email code": "Unesite kod iz emaila",
  "Open teacher workspace": "Otvori nastavnički prostor",
  "Send sign-in link": "Pošalji link za prijavu",
  "Use a different email": "Koristi drugi email",
  "Teacher accounts are invited by your school.": "Škola poziva nastavničke račune.",
  "That code is invalid or has expired. Please try again.": "Kod je nevažeći ili je istekao. Pokušajte ponovo.",
  "Sign in as a teacher": "Prijavi se kao nastavnik",
  "Getting things ready…": "Pripremamo sve…",
  "One moment…": "Trenutak…",
  "ALL SET": "SVE JE SPREMNO",
  "Please try again.": "Pokušajte ponovo.",
  "Try again": "Pokušaj ponovo",
  "A LITTLE OFF THE MAP": "MALO IZVAN MAPE",
  "Let’s head back to the commons.": "Vratimo se u školski prostor.",
  "This page isn’t here. Your school space is just one click away.": "Stranica nije pronađena. Školski prostor je udaljen jedan klik.",
  "A SMALL PAUSE": "MALA PAUZA",
  "Let’s give that another try.": "Pokušajmo ponovo.",
  "We couldn’t open this page. Please try again in a moment.": "Nismo uspjeli otvoriti stranicu. Pokušajte uskoro ponovo.",
  "Close": "Zatvori",
  "Terms of service": "Uslovi korištenja",
  "Privacy policy": "Politika privatnosti",
  "Skip to content": "Preskoči na sadržaj",
  "Guide": "Vodič",
  "Got it": "Razumijem",
  "Open this tool’s guide": "Otvori vodič ovog alata",
  "A LITTLE HELP TO GET STARTED": "MALA POMOĆ ZA POČETAK",
  "This guide appears once per tool in this browser. Open Guide anytime to read it again.": "Ovaj vodič se prikazuje jednom po alatu u ovom pregledniku. Ponovo ga otvorite dugmetom Vodič.",
  "Welcome to SchoolHub": "Dobro došli u SchoolHub",
  "Students verify their school email without creating an account. Teachers sign in with an invited school email.": "Učenici potvrđuju školski email bez kreiranja računa. Nastavnici se prijavljuju pozvanim školskim emailom.",
  "Choose a tool from the menu. You can switch between English and Bosnian at any time.": "Odaberite alat iz menija. U svakom trenutku možete promijeniti jezik između engleskog i bosanskog.",
  "A guide to anonymous questions": "Vodič za anonimna pitanja",
  "Choose a teacher, department, or school life and write your question.": "Odaberite nastavnika, odsjek ili školski život i napišite pitanje.",
  "Choose Private to keep it with authorized staff, or Public to share it anonymously with other students.": "Odaberite Privatno da pitanje ostane kod ovlaštenog osoblja ili Javno da ga anonimno podijelite s drugim učenicima.",
  "Save your private receipt link after submitting. Open it later to read the teacher’s answer. Public questions and replies also appear below the form.": "Nakon slanja sačuvajte privatni link potvrde. Kasnije ga otvorite za čitanje odgovora. Javna pitanja i odgovori prikazuju se i ispod obrasca.",
  "A guide to class boards": "Vodič za razredne ploče",
  "Find your teacher’s board and open it to read pinned public questions and answers.": "Pronađite nastavnikovu ploču i otvorite je da pročitate prikvačena javna pitanja i odgovore.",
  "Private questions can never be pinned. No student account is needed.": "Privatna pitanja se nikada ne mogu prikvačiti. Učenički račun nije potreban.",
  "A guide to Library Table": "Vodič za stol za učenje",
  "Filter sessions by programme, grade, subject, place, or date.": "Filtrirajte termine po programu, razredu, predmetu, mjestu ili datumu.",
  "To host a session, choose your grade and IB or National programme, type the meeting place, and select a date and start/end hours.": "Za organizovanje odaberite razred i IB ili nacionalni program, unesite mjesto te datum i početni i završni sat.",
  "Save your private management link to edit or cancel your session. Sessions disappear from the active board when they end.": "Sačuvajte privatni link za izmjene ili otkazivanje. Termini nestaju s aktivne ploče nakon završetka.",
  "A guide to debates": "Vodič za debate",
  "Your teacher creates the debate. Scan their QR code or enter the six-character room code.": "Nastavnik kreira debatu. Skenirajte QR kod ili unesite kod sobe od šest znakova.",
  "Enter a name your teacher recognizes. Wait for them to assign balanced stances.": "Unesite ime koje nastavnik prepoznaje. Sačekajte ravnomjernu dodjelu stavova.",
  "Your stance appears on your phone. Prepare with your group, then debate in person.": "Stav se prikazuje na telefonu. Pripremite se s grupom, a zatim debatujte uživo.",
  "A guide to the noise monitor": "Vodič za mjerač buke",
  "Press Start noise monitor and allow microphone access.": "Pritisnite Pokreni mjerač buke i dozvolite pristup mikrofonu.",
  "Green means calm, yellow means rising volume, and red is a reminder to quiet down. Adjust sensitivity or calibrate a quiet room.": "Zeleno znači mirno, žuto porast glasnoće, a crveno podsjeća da se stiša. Podesite osjetljivost ili kalibrirajte tihu prostoriju.",
  "Audio is processed only in this browser. Nothing is recorded or uploaded. Stop the monitor to release the microphone.": "Zvuk se obrađuje samo u pregledniku. Ništa se ne snima niti šalje. Zaustavite mjerač da oslobodite mikrofon.",
  "A guide to your teacher workspace": "Vodič za nastavnički prostor",
  "Your inbox includes questions sent to you and your assigned departments. Write and save answers directly on question cards.": "Pretinac sadrži pitanja upućena vama i vašim odsjecima. Pišite i čuvajte odgovore direktno na karticama pitanja.",
  "Public answers are shared with the school. Private answers are available through the student’s receipt link. Only public questions can be pinned to boards.": "Javni odgovori se dijele sa školom. Privatni odgovori su dostupni putem učeničkog linka potvrde. Samo javna pitanja se mogu prikvačiti na ploče.",
  "Create debates, share the QR with your class, and assign stances when everyone has joined.": "Kreirajte debate, podijelite QR kod s razredom i dodijelite stavove kada se svi pridruže.",
  "A guide to school settings": "Vodič za školske postavke",
  "Invite teachers using their school email, then assign department and school-life inbox access.": "Pozovite nastavnike školskim emailom, zatim dodijelite pristup pretincima odsjeka i školskog života.",
  "Review flagged questions and keep the subject and department directory up to date.": "Pregledajte označena pitanja i ažurirajte imenik predmeta i odsjeka.",
  "A guide to your receipt": "Vodič za vašu potvrdu",
  "This private link lets you read the teacher’s answer without an account. Keep it somewhere safe.": "Ovaj privatni link omogućava čitanje odgovora bez računa. Čuvajte ga na sigurnom mjestu.",
  "Anyone holding the link can read this question and reply. Use Check for an answer to refresh it.": "Svako s linkom može čitati pitanje i odgovor. Koristite Provjeri odgovor za osvježavanje.",
  "A guide to teacher sign-in": "Vodič za nastavničku prijavu",
  "Use the school email invited by your administrator. Open the emailed sign-in link or enter its code.": "Koristite školski email koji je administrator pozvao. Otvorite link iz emaila ili unesite kod.",
  "Students verify their school email instead of creating an account.": "Učenici potvrđuju školski email umjesto kreiranja računa.",
  "About the terms of service": "O uslovima korištenja",
  "Read the school-use rules here. For questions about the service, contact your school administration.": "Ovdje pročitajte pravila školskog korištenja. Za pitanja o usluzi obratite se upravi škole.",
  "About your privacy": "O vašoj privatnosti",
  "Read how questions, teacher accounts, study sessions, device permissions, and browser preferences are handled.": "Pročitajte kako se obrađuju pitanja, nastavnički računi, termini, dozvole uređaja i postavke preglednika.",
  "Hello": "Zdravo",
  "new": "novo",
  "answered": "odgovoreno",
  "archived": "arhivirano",
  "teacher": "nastavnik",
  "admin": "administrator",
  "minute": "minuta",
  "minutes": "minuta",
  "Stance": "Stav",
  "Remove stance": "Ukloni stav",
  "SCAN TO JOIN THE ROOM": "SKENIRAJ ZA PRIDRUŽIVANJE",
  "SCAN TO JOIN ·": "SKENIRAJ ZA PRIDRUŽIVANJE ·",
  "/ 100 joined": "/ 100 pridruženih",
  "joined. Your teacher will assign your stance when the class is ready.": "pridruženo. Nastavnik će dodijeliti stav kada razred bude spreman.",
  "Check your email for a sign-in link. If your school uses email codes, enter the code below.": "Provjerite email za link prijave. Ako škola koristi email kodove, unesite kod ispod.",
  "Mathematics": "Matematika",
  "Natural Sciences": "Prirodne nauke",
  "Humanities": "Društvene nauke",
  "Languages": "Jezici",
  "Arts & Technology": "Umjetnost i tehnologija",
  "Physics": "Fizika",
  "Chemistry": "Hemija",
  "Biology": "Biologija",
  "English": "Engleski",
  "History": "Historija",
  "Geography": "Geografija",
  "Computer Science": "Informatika",
  "Visual Arts": "Likovna umjetnost",
  "Your school's tools are being connected. Please try again shortly.": "Školski alati se povezuju. Pokušajte ponovo uskoro.",
  "That selection is no longer available. Refresh and choose again.": "Odabir više nije dostupan. Osvježite i odaberite ponovo.",
  "This already exists. Try a different name or reload.": "Ovo već postoji. Pokušajte s drugim nazivom ili osvježite.",
  "The request could not be completed. Please try again.": "Zahtjev nije dovršen. Pokušajte ponovo.",
  "Request origin is not allowed.": "Izvor zahtjeva nije dozvoljen.",
  "Request is too large.": "Zahtjev je prevelik.",
  "Invalid request.": "Nevažeći zahtjev.",
  "Please sign in as a teacher.": "Prijavite se kao nastavnik.",
  "Your account does not have teacher access.": "Vaš račun nema nastavnički pristup.",
  "You've made several submissions. Please wait a few minutes and try again.": "Poslali ste više objava. Sačekajte nekoliko minuta i pokušajte ponovo.",
  "The school is receiving many submissions. Please try again shortly.": "Škola prima mnogo objava. Pokušajte ponovo uskoro.",
  "Please check your entries.": "Provjerite unesene podatke.",
  "Something went wrong. Please try again.": "Došlo je do greške. Pokušajte ponovo.",
  "Write at least 3 characters.": "Napišite najmanje 3 znaka.",
  "Keep your question within 280 characters.": "Pitanje mora imati najviše 280 znakova.",
  "Submission rejected.": "Slanje je odbijeno.",
  "Choose a teacher or department.": "Odaberite nastavnika ili odsjek.",
  "Type your meeting place.": "Unesite mjesto sastanka.",
  "End time must be after start time.": "Završetak mora biti nakon početka.",
  "A session can last up to 12 hours.": "Termin može trajati najviše 12 sati.",
  "Each stance must have a different name.": "Svaki stav mora imati različit naziv.",
  "A debate needs 2–4 stances.": "Debata treba imati 2–4 stava.",
  "Choose a date and time.": "Odaberite datum i vrijeme.",
  "Invalid date.": "Nevažeći datum.",
  "This time does not exist due to daylight saving. Choose another time.": "Ovo vrijeme ne postoji zbog pomjeranja sata. Odaberite drugo vrijeme.",
  "This private receipt is unavailable.": "Privatna potvrda nije dostupna.",
  "Please use a classroom-appropriate answer.": "Koristite odgovor primjeren učionici.",
  "Choose an available teacher.": "Odaberite dostupnog nastavnika.",
  "Choose a session that has not ended.": "Odaberite termin koji nije završen.",
  "Post sessions up to 30 days ahead.": "Termine možete objaviti do 30 dana unaprijed.",
  "Meeting places are unavailable. Apply the database migrations.": "Mjesta sastanka nisu dostupna. Potrebno je primijeniti migracije baze.",
  "This management link is invalid.": "Link za upravljanje nije važeći.",
  "Session details are required.": "Podaci termina su obavezni.",
  "This session has been cancelled.": "Termin je otkazan.",
  "Please use a classroom-appropriate name.": "Koristite ime primjereno učionici.",
  "Board unavailable.": "Ploča nije dostupna.",
  "Board not found.": "Ploča nije pronađena.",
  "Debate not found or expired.": "Debata nije pronađena ili je istekla.",
  "Lobby not found or expired. Check your join code.": "Čekaonica nije pronađena ili je istekla. Provjerite kod.",
  "School administrator access required.": "Potreban je pristup školskog administratora.",
  "Administrator access required.": "Potreban je administratorski pristup.",
  "Enter a board title.": "Unesite naziv ploče.",
  "Choose a pinned question.": "Odaberite prikvačeno pitanje.",
  "Invitation could not be sent. Check the email address and your school's email settings.": "Poziv nije poslan. Provjerite email adresu i školske email postavke.",
  "Use 3–60 lowercase letters, numbers, and hyphens.": "Koristite 3–60 malih slova, brojeva i crtica.",
  "Debate unavailable.": "Debata nije dostupna.",
  "Let students join before assigning stances.": "Sačekajte da se učenici pridruže prije dodjele stavova.",
  "Choose a participant.": "Odaberite učesnika.",
  "Question unavailable": "Pitanje nije dostupno",
  "Teacher unavailable": "Nastavnik nije dostupan",
  "Private questions cannot be published": "Privatna pitanja se ne mogu objaviti",
  "Choose one of your boards": "Odaberite jednu od svojih ploča",
  "Review and approve this question before publishing": "Pregledajte i odobrite pitanje prije objave",
  "Restore this question before publishing": "Vratite pitanje prije objave",
  "Restore this question before answering": "Vratite pitanje prije odgovaranja",
  "Write an answer of 1-2000 characters": "Napišite odgovor od 1 do 2000 znakova",
  "Supabase's email sending limit has been reached. Wait before trying again, or ask your administrator to configure custom SMTP in Supabase.": "Dostignuto je Supabase ograničenje slanja emaila. Sačekajte ili zamolite administratora da podesi vlastiti SMTP u Supabaseu.",
  "Too many sign-in attempts. Wait a few minutes before trying again.": "Previše pokušaja prijave. Sačekajte nekoliko minuta i pokušajte ponovo.",
  "Supabase's default email service cannot send to this address. Your administrator needs to configure custom SMTP in Supabase.": "Zadana Supabase email usluga ne može slati na ovu adresu. Administrator treba podesiti vlastiti SMTP.",
  "Open your teacher invitation email and confirm your account first, then sign in.": "Otvorite nastavnički poziv u emailu i prvo potvrdite račun, zatim se prijavite.",
  "Use the email address from your teacher invitation. Ask your school administrator to invite you if you do not have an invitation.": "Koristite email iz nastavničkog poziva. Ako nemate poziv, zatražite ga od školskog administratora.",
  "Email sign-in is disabled. Your administrator needs to enable email sign-in in Supabase Authentication.": "Email prijava je isključena. Administrator je treba uključiti u Supabase Authentication postavkama.",
  "Too many sign-in requests. Wait before trying again.": "Previše zahtjeva za prijavu. Sačekajte prije ponovnog pokušaja.",
  "Could not send your sign-in link. Please try again.": "Link za prijavu nije poslan. Pokušajte ponovo.",
  "Arts & Design": "Umjetnost i dizajn",
  "student has": "učenik se",
  "students have": "učenika se",
  "reopen": "ponovo otvori"
};
