"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, AudioLines, BookOpen, Check, Library, LockKeyhole, MessageCircle, MessagesSquare, MoveUpRight, Pin, Sparkles, Users } from "lucide-react";
import { PageIntro, SmallLink, useResource } from "@/components/ui";
import { schoolDate, schoolTime, programmeClass, type StudySession } from "@/lib/domain";
export default function Home() {
  const { data: studies } = useResource<StudySession[]>("studies", 60000);
  const { data: boards } = useResource<{ id: string; slug: string; title: string }[]>("boards");
  const today = (studies || []).filter(s => schoolDate(new Date(s.starts_at)) === schoolDate()).slice(0, 3);
  return <>
    <PageIntro eyebrow="A LITTLE MORE CONNECTED" title="Your school. Your space." description="Ask the question. Find your people. Make today a little better." action={<span className="intro-stamp"><Sparkles size={17} /> Made for the moments between classes</span>} />
    <section className="home-tools" aria-label="SchoolHub tools">
      <Link href="/ask" className="tool-card ask-card"><div className="tool-top"><span className="tool-icon"><MessageCircle size={22} /></span><span className="card-category">SPEAK YOUR MIND</span><ArrowUpRight size={21} /></div><div className="ask-content"><h2>Big question?<br />Small suggestion?<br /><em>We’re listening.</em></h2><p>A direct line to your teachers and school.<br />Always anonymous. Always welcome.</p><span className="card-button">Ask a question <ArrowRight size={16} /></span></div><div className="question-art" aria-hidden="true"><div className="art-note"><span className="note-tape" /><span className="art-line" /><span className="art-line short" /><span className="art-question">?</span><span className="art-anon"><LockKeyhole size={12} /> just your voice</span></div><span className="art-star star-one">✳</span><span className="art-star star-two">✧</span><svg className="art-loop" viewBox="0 0 100 80"><path d="M10 60 C20 15 80 5 80 35 C80 70 35 70 42 35 C45 15 65 10 90 15" /><path d="M82 6 L92 15 L80 22" /></svg></div><div className="card-bottom"><LockKeyhole size={13} /> No name. No account. No awkwardness.</div></Link>
      <Link href="/library" className="tool-card library-card"><div className="tool-top"><span className="tool-icon"><Library size={22} /></span><span className="card-category">LEARN TOGETHER</span><ArrowUpRight size={21} /></div><h2>There’s a seat<br />at the table.</h2><p>Find a study group, share what you know,<br />or start something of your own.</p><div className="library-art" aria-hidden="true"><span className="art-book book-one">IB</span><span className="art-book book-two">National</span><span className="art-book book-three"><BookOpen size={24} /></span><span className="book-spark">✳</span></div><span className="card-button">Find your study group <ArrowRight size={16} /></span><div className="card-bottom"><Users size={13} /> Better together, one session at a time.</div></Link>
      <Link href="/debate" className="tool-card compact-card debate-card"><div className="compact-icon"><MessagesSquare size={24} /></div><div><span className="card-category">A DIFFERENT PERSPECTIVE</span><h2>Let’s take a side.</h2><p>Join a classroom debate. Bring your voice.</p></div><span className="round-arrow"><ArrowUpRight size={21} /></span></Link>
      <Link href="/noise" className="tool-card compact-card noise-card"><div className="compact-icon"><AudioLines size={24} /></div><div><span className="card-category">ROOM TO FOCUS</span><h2>A little quieter.</h2><p>A gentle nudge toward a calmer classroom.</p></div><span className="round-arrow"><ArrowUpRight size={21} /></span></Link>
    </section>
    <div className="home-bottom"><section className="today-section"><div className="section-heading"><h2>At the table today <span className="count-badge">{today.length}</span></h2><SmallLink href="/library">See the board</SmallLink></div><div className="today-list">{today.length ? today.map(s => <Link href="/library" className="today-row" key={s.id}><span className={`subject-symbol ${programmeClass(s.programme)}`}><BookOpen size={18} /></span><div><strong>{s.subject.name}: {s.focus}</strong><span>{s.custom_location || s.location.name} <span className="dot-separator">·</span> {schoolTime(s.starts_at)}–{schoolTime(s.ends_at)}</span></div><span className={`tag ${programmeClass(s.programme)}`}>{s.programme}</span><MoveUpRight size={16} /></Link>) : <div className="today-empty"><span className="empty-mini-icon"><Library size={26} /></span><div><strong>The next great study session starts with you.</strong><p>Pull up a chair. Invite someone to learn together.</p></div><Link href="/library/new" className="button secondary small">Start a session <ArrowRight size={15} /></Link></div>}</div></section><aside className="commons-note"><span className="eyebrow"><Pin size={14} /> FROM THE COMMONS</span><h3>Every voice <br />makes a difference.</h3><p>{boards?.length ? "See what your teachers have shared with the school community." : "A thoughtful question can start a conversation that changes someone’s day."}</p>{boards?.length ? <SmallLink href="/boards">Browse class boards</SmallLink> : <SmallLink href="/ask">Share what’s on your mind</SmallLink>}<span className="commons-check"><Check size={14} /> Your questions stay private until a teacher shares them.</span></aside></div>
  </>;
}
