"use client";
import Link from "next/link";
import { useLanguage } from "./language";
type Section = { title: string; text: string };
const terms: Record<"en" | "bs", Section[]> = {
  en: [
    { title: "Who the service is for", text: "SchoolHub supports school questions, peer study, classroom debates, and a local noise monitor. Use it as part of your school community and follow your school’s rules. Teachers need an invited account; students can use student tools without registering." },
    { title: "Respectful and safe use", text: "Be respectful. Do not post harassment, threats, discriminatory content, sexual content, spam, impersonation, or another person’s private information. Do not attempt to bypass access controls or disrupt the service. Avoid sharing your full name, phone number, address, health information, or other sensitive details in questions." },
    { title: "Questions and visibility", text: "You choose whether a question is private or public before submitting it. Public questions and answers can be read by anyone visiting the public Q&A feed and can be pinned to class boards. Private questions are available to authorized staff and anyone holding the private receipt link. Questions do not include a student account or email. Staff may review, archive, and moderate submissions; an answer is not guaranteed." },
    { title: "Study sessions and debates", text: "Study sessions are public posts, including any name or contact handle you choose to provide. Hosts are responsible for accurate details and arranging safe meetings in appropriate school spaces. Open spots are informational rather than reservations. Teachers run debates and may remove participants. Keep private receipt and session-management links safe: anyone holding them can access their associated controls or content." },
    { title: "Availability and responsibility", text: "Features may change or be temporarily unavailable. SchoolHub is not an emergency reporting channel, an official assessment system, or a guarantee of supervision. For urgent safety concerns, contact a trusted adult or the appropriate emergency service directly. The noise monitor provides a relative indication, not a calibrated sound measurement." },
    { title: "Content, moderation, and contact", text: "You remain responsible for what you submit. Submitting content allows SchoolHub and authorized school staff to store and display it according to the visibility you select, solely to operate these school tools. School staff may restrict access or remove inappropriate content. Contact your school administration about moderation, access, or these terms. Changes to these terms will be dated on this page." },
  ],
  bs: [
    { title: "Kome je usluga namijenjena", text: "SchoolHub omogućava školska pitanja, zajedničko učenje, razredne debate i lokalni mjerač buke. Koristite ga u okviru svoje školske zajednice i poštujte školska pravila. Nastavnicima je potreban pozvani račun; učenici mogu koristiti svoje alate bez registracije." },
    { title: "Odgovorno i sigurno korištenje", text: "Budite obzirni. Zabranjeni su uznemiravanje, prijetnje, diskriminacija, seksualni sadržaj, neželjene poruke, lažno predstavljanje i objavljivanje tuđih privatnih podataka. Ne zaobilazite zaštitu pristupa i ne ometajte uslugu. U pitanjima ne dijelite puno ime, broj telefona, adresu, zdravstvene podatke ili druge osjetljive informacije." },
    { title: "Pitanja i vidljivost", text: "Prije slanja birate hoće li pitanje biti privatno ili javno. Javna pitanja i odgovore može čitati svako na javnoj listi pitanja, a nastavnici ih mogu prikvačiti na razredne ploče. Privatna pitanja dostupna su ovlaštenom osoblju i svakome ko ima privatni link potvrde. Pitanja ne sadrže učenički račun ili email. Osoblje može pregledati, arhivirati i moderirati objave; odgovor nije zagarantovan." },
    { title: "Termini učenja i debate", text: "Termini učenja su javne objave, uključujući ime ili kontakt koji odlučite navesti. Organizatori su odgovorni za tačne podatke i sigurne sastanke u odgovarajućim školskim prostorima. Broj slobodnih mjesta je informativan i ne predstavlja rezervaciju. Nastavnici vode debate i mogu ukloniti učesnike. Čuvajte privatne linkove potvrda i upravljanja terminima: svako ko ih ima može pristupiti povezanim sadržajima ili kontrolama." },
    { title: "Dostupnost i odgovornost", text: "Funkcije se mogu mijenjati ili privremeno biti nedostupne. SchoolHub nije kanal za hitne prijave, službeni sistem ocjenjivanja niti garancija nadzora. Za hitne sigurnosne probleme obratite se odrasloj osobi od povjerenja ili odgovarajućoj hitnoj službi. Mjerač buke daje relativnu procjenu, a ne kalibrirano mjerenje zvuka." },
    { title: "Sadržaj, moderiranje i kontakt", text: "Odgovorni ste za sadržaj koji šaljete. Slanjem dopuštate SchoolHubu i ovlaštenom školskom osoblju da ga pohrane i prikažu u skladu s odabranom vidljivošću, isključivo radi rada školskih alata. Školsko osoblje može ograničiti pristup ili ukloniti neprikladan sadržaj. Za pitanja o moderiranju, pristupu ili ovim uslovima obratite se upravi škole. Izmjene uslova bit će označene datumom na ovoj stranici." },
  ],
};
const privacy: Record<"en" | "bs", Section[]> = {
  en: [
    { title: "Questions and answers", text: "We store question text, its recipient, visibility, moderation status, dates, and any teacher answer. We do not attach a student name, account, or email to questions. A random receipt token lets you read a reply; only its hash is stored in the database. Public questions and answers are visible to other visitors. Private ones are limited to authorized staff and holders of the receipt link. Anonymous does not mean that hosting providers have no request metadata." },
    { title: "Teacher accounts and classroom tools", text: "Invited teacher accounts use an email address, display name, assigned departments, and access role. Supabase handles authentication and associated security logs. Staff moderation and administrative actions are recorded. Debate sessions store the prompt, stances, participant display names, assignments, and hashed participant tokens. A browser cookie restores a participant’s place. Teachers can see the roster." },
    { title: "Study sessions", text: "We store the programme, grade, subject, topic, meeting place, date, hours, and open spots. The optional host name and contact handle are public with the session. A hashed management token protects editing and cancellation. Share only contact details you are comfortable making public." },
    { title: "Device permissions", text: "The QR scanner requests camera access when you start scanning. Frames are processed locally to read the debate code and are not uploaded or saved by SchoolHub. The noise monitor requests microphone access when you start it. Audio is processed locally and is not recorded, uploaded, or stored by SchoolHub. Stop these tools or leave their page to release the device." },
    { title: "Browser storage and security", text: "Local browser storage remembers your language, role preference, and which guides you dismissed. Authentication and debate cookies support sign-in and lobby access. A temporary browser cookie and expiring hashed rate-limit buckets help prevent spam; on Vercel, a hashed network address is also used for broad abuse limits. These limits are not attached to question rows. Clearing browser storage resets preferences and guides and may end your session." },
    { title: "Hosting and retention", text: "Vercel hosts the app and Supabase provides the database and authentication. They may process request metadata and operational or security logs under their own service policies. Questions, answers, teacher profiles, and staff actions remain stored until school administrators delete them; archiving is not deletion. Study sessions disappear from the active board after their end time, and debate lobbies expire after 24 hours. If the optional cleanup migration is enabled, it removes expired debates, expired rate-limit buckets, and study sessions whose end time is more than seven days old. Provider backups and logs have separate retention settings." },
    { title: "Requests and contact", text: "Contact your school administration about access, correction, deletion, retention, or privacy concerns. For an anonymous question, provide its receipt securely so staff can identify the correct record. Never post your receipt publicly. The school operating this deployment determines who administers it and how long its records should be kept. This page describes SchoolHub’s implemented behavior; contact your school for its additional data-handling rules." },
  ],
  bs: [
    { title: "Pitanja i odgovori", text: "Pohranjujemo tekst pitanja, primaoca, vidljivost, status moderiranja, datume i odgovor nastavnika. Uz pitanja ne povezujemo ime učenika, račun ili email. Nasumični token potvrde omogućava čitanje odgovora; u bazi se čuva samo njegov hash. Javna pitanja i odgovori vidljivi su drugim posjetiocima. Privatna su dostupna ovlaštenom osoblju i osobama koje imaju link potvrde. Anonimnost ne znači da hosting pružaoci nemaju metapodatke o zahtjevima." },
    { title: "Nastavnički računi i razredni alati", text: "Pozvani nastavnički računi koriste email, prikazano ime, dodijeljene odsjeke i ulogu pristupa. Supabase upravlja prijavom i povezanim sigurnosnim zapisima. Bilježe se radnje moderiranja i administracije. Debate čuvaju temu, stavove, prikazana imena učesnika, raspored i hash vrijednosti tokena učesnika. Kolačić preglednika vraća učesnika na njegovo mjesto. Nastavnik može vidjeti listu učesnika." },
    { title: "Termini učenja", text: "Pohranjujemo program, razred, predmet, temu, mjesto sastanka, datum, satnicu i slobodna mjesta. Neobavezno ime organizatora i kontakt javno su prikazani uz termin. Hash tokena za upravljanje štiti izmjene i otkazivanje. Dijelite samo kontakt podatke koje želite učiniti javnim." },
    { title: "Dozvole uređaja", text: "QR skener traži pristup kameri kada pokrenete skeniranje. Slike se lokalno obrađuju radi čitanja koda debate i SchoolHub ih ne šalje niti pohranjuje. Mjerač buke traži pristup mikrofonu kada ga pokrenete. Zvuk se obrađuje lokalno i SchoolHub ga ne snima, ne šalje niti pohranjuje. Zaustavite alat ili napustite stranicu da biste oslobodili uređaj." },
    { title: "Pohrana u pregledniku i sigurnost", text: "Lokalna pohrana pamti jezik, odabranu ulogu i vodiče koje ste zatvorili. Kolačići za prijavu i debate omogućavaju pristup računu i čekaonici. Privremeni kolačić i vremenski ograničene hash vrijednosti ograničavaju neželjene objave; na Vercelu se za širu zaštitu koristi i hash mrežne adrese. Ova ograničenja nisu povezana s redovima pitanja. Brisanje podataka preglednika resetuje postavke i vodiče i može završiti sesiju." },
    { title: "Hosting i čuvanje podataka", text: "Vercel pruža hosting, a Supabase bazu i prijavu. Mogu obrađivati metapodatke zahtjeva i operativne ili sigurnosne zapise prema vlastitim pravilima. Pitanja, odgovori, nastavnički profili i radnje osoblja čuvaju se dok ih školski administratori ne izbrišu; arhiviranje nije brisanje. Termini nestaju s aktivne ploče po završetku, a čekaonice debata ističu nakon 24 sata. Ako je uključena neobavezna migracija za čišćenje, briše istekle debate, istekle zapise ograničenja i termine završene prije više od sedam dana. Sigurnosne kopije i zapisi pružalaca imaju zasebne postavke čuvanja." },
    { title: "Zahtjevi i kontakt", text: "Za pristup, ispravke, brisanje, rokove čuvanja ili privatnost obratite se upravi škole. Za anonimno pitanje sigurno dostavite njegovu potvrdu kako bi osoblje pronašlo pravi zapis. Nikada javno ne dijelite link potvrde. Škola koja koristi ovu instalaciju određuje administratore i rokove čuvanja. Ova stranica opisuje rad SchoolHuba; za dodatna pravila obrade podataka obratite se školi." },
  ],
};
export function LegalPage({ type }: { type: "terms" | "privacy" }) {
  const { language, t } = useLanguage();
  const sections = (type === "terms" ? terms : privacy)[language];
  return <article className="legal-page"><span className="eyebrow">SCHOOLHUB</span><h1>{type === "terms" ? t("Terms of service") : t("Privacy policy")}</h1><p className="field-help">{language === "bs" ? "Posljednja izmjena: 7. oktobar 2026." : "Last updated: 7 October 2026."}</p>{sections.map(section => <section key={section.title}><h2>{section.title}</h2><p>{section.text}</p></section>)}{type === "privacy" && <p><a href="https://supabase.com/privacy" target="_blank" rel="noreferrer">Supabase — {t("Privacy policy")}</a> · <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Vercel — {t("Privacy policy")}</a></p>}<Link href={type === "terms" ? "/privacy" : "/terms"}>{type === "terms" ? t("Privacy policy") : t("Terms of service")}</Link></article>;
}
