"use client";
import { useLanguage } from "@/components/language";
import { useCallback, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, GraduationCap, MessagesSquare, ScanLine } from "lucide-react";
import { QrScanner } from "@/components/debate-tools";
import { PageIntro } from "@/components/ui";
export default function DebatePage() {
  const { t } = useLanguage();
  const [code, setCode] = useState(""); const router = useRouter(); const [scanning, setScanning] = useState(false);
  const handleScan = useCallback((scanned: string) => { setScanning(false); router.push(`/debate/join/${scanned}`); }, [router]);
  return <><PageIntro eyebrow={t("THE DEBATE ROOM")} title={t("A different point of view.")} description={t("Join your classroom debate. Find your side. Bring your voice.")} /><div className="form-layout"><section className="form-panel"><span className="tool-icon" style={{ background: "#f0eade", color: "#a08b64" }}><MessagesSquare size={23} /></span><h2 style={{ marginTop: 20 }}>{t("Your class is waiting.")}</h2><p>{t("Scan the QR on your teacher’s screen, or enter the six-character room code.")}</p>{scanning ? <QrScanner onScan={handleScan} onCancel={() => setScanning(false)} /> : <><form className="join-code-form" onSubmit={e => { e.preventDefault(); router.push(`/debate/join/${code.toUpperCase()}`); }}><label style={{ flex: 1 }}><span className="field-label">{t("Room code")}</span><input className="input join-code-input" value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="ABC123" minLength={6} maxLength={6} pattern="[A-Z0-9]{6}" required autoComplete="off" aria-label={t("Six-character room code")} /></label><button className="button primary" style={{ marginTop: 21 }} type="submit">{t("Join")}<ArrowRight size={16} /></button></form><button className="button secondary" type="button" style={{ marginTop: 12, width: "100%" }} onClick={() => setScanning(true)}><ScanLine size={16} /> {t("Scan QR code")}</button></>}<p className="privacy-note" style={{ marginTop: 19, marginBottom: 0 }}>{t("No account needed. Just a name your teacher will recognize.")}</p></section><aside className="info-panel"><GraduationCap size={27} strokeWidth={1.5} /><h3>{t("Bring a room")}<br />{t("full of ideas together.")}</h3><p>{t("Teachers set the prompt and stances. SchoolHub takes care of the lobby, fair assignments, and prep timer.")}</p><div className="info-panel-foot">{t("Speaking and debating happen in person. The phones just help everyone get into place.")}</div></aside></div><div className="debate-how">{[["01", "Join the room", "Scan the QR or enter your teacher’s code. Your phone becomes your place in the lobby."], ["02", "Meet your perspective", "The teacher shuffles the class into balanced sides. Your assigned stance appears on your phone."], ["03", "Make your case", "Prepare together while the timer runs. Then put the phones down and start the conversation."]].map(([n, title, desc]) => <div className="how-card" key={n}><span className="info-number">{n}</span><h3>{t(title)}</h3><p>{t(desc)}</p></div>)}</div></>;
}
