"use client";
import Link from "next/link";
import { useCallback, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, GraduationCap, MessagesSquare, ScanLine } from "lucide-react";
import { QrScanner } from "@/components/debate-tools";
import { PageIntro } from "@/components/ui";
export default function DebatePage() {
  const [code, setCode] = useState(""); const router = useRouter(); const [scanning, setScanning] = useState(false);
  const handleScan = useCallback((scanned: string) => { setScanning(false); router.push(`/debate/join/${scanned}`); }, [router]);
  return <><PageIntro eyebrow="THE DEBATE ROOM" title="A different point of view." description="Join your classroom debate. Find your side. Bring your voice." /><div className="form-layout"><section className="form-panel"><span className="tool-icon" style={{ background: "#f0eade", color: "#a08b64" }}><MessagesSquare size={23} /></span><h2 style={{ marginTop: 20 }}>Your class is waiting.</h2><p>Scan the QR on your teacher’s screen, or enter the six-character room code.</p>{scanning ? <QrScanner onScan={handleScan} onCancel={() => setScanning(false)} /> : <><form className="join-code-form" onSubmit={e => { e.preventDefault(); router.push(`/debate/join/${code.toUpperCase()}`); }}><label style={{ flex: 1 }}><span className="field-label">Room code</span><input className="input join-code-input" value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="ABC123" minLength={6} maxLength={6} pattern="[A-Z0-9]{6}" required autoComplete="off" aria-label="Six-character room code" /></label><button className="button primary" style={{ marginTop: 21 }} type="submit">Join <ArrowRight size={16} /></button></form><button className="button secondary" type="button" style={{ marginTop: 12, width: "100%" }} onClick={() => setScanning(true)}><ScanLine size={16} /> Scan QR code</button></>}<p className="privacy-note" style={{ marginTop: 19, marginBottom: 0 }}>No account needed. Just a name your teacher will recognize.</p></section><aside className="info-panel"><GraduationCap size={27} strokeWidth={1.5} /><h3>Bring a room<br />full of ideas together.</h3><p>Teachers set the prompt and stances. SchoolHub takes care of the lobby, fair assignments, and prep timer.</p><Link href="/teacher/debates/new" className="button secondary" style={{ marginTop: 24 }}>Start a classroom debate <ArrowRight size={15} /></Link><div className="info-panel-foot">Speaking and debating happen in person. The phones just help everyone get into place.</div></aside></div><div className="debate-how">{[["01", "Join the room", "Scan the QR or enter your teacher’s code. Your phone becomes your place in the lobby."], ["02", "Meet your perspective", "The teacher shuffles the class into balanced sides. Your assigned stance appears on your phone."], ["03", "Make your case", "Prepare together while the timer runs. Then put the phones down and start the conversation."]].map(([n, title, desc]) => <div className="how-card" key={n}><span className="info-number">{n}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></>;
}
