"use client";
import { useLanguage } from "@/components/language";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, GraduationCap, LockKeyhole, MessageCircle, School, ShieldCheck, Users } from "lucide-react";
import { api } from "@/lib/api-client";
import { type Config } from "@/lib/domain";
import { ErrorMessage, PageIntro, SubmitButton, Success, useResource } from "@/components/ui";
type PublicQuestion = { id: string; body: string; status: string; answer: string | null };
export default function AskPage() {
  const { t } = useLanguage();
  const { data: config, error: configError, loading } = useResource<Config>("config");
  const { data: publicQuestions, error: feedError, refresh: refreshFeed } = useResource<PublicQuestion[]>("questions", 30000);
  const [visibility, setVisibility] = useState<"private" | "public">("private"), [receipt, setReceipt] = useState("");
  const [copied, setCopied] = useState(false);
  const [recipientType, setType] = useState<"teacher" | "department" | "general">("department");
  const [recipientId, setId] = useState(""); const [body, setBody] = useState("");
  const [error, setError] = useState<string | null>(null), [pending, setPending] = useState(false), [done, setDone] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError(null);
    try { const fields = new FormData(event.currentTarget); const result = await api<{ id: string; receiptToken: string }>("questions", { visibility, body, recipientType, recipientId: recipientType === "general" ? null : recipientId, website: fields.get("website") || "" }); setReceipt(`${window.location.origin}/question/${result.id}#key=${result.receiptToken}`); setCopied(false); setDone(true); void refreshFeed(); }
    catch (e) { setError((e as Error).message); } finally { setPending(false); }
  }
  return <><PageIntro eyebrow={t("THE OPEN SCHOOL BACKCHANNEL")} title={t("What’s on your mind?")} description={t("A question, an idea, or something we could do better. Your voice belongs here.")} />
    <div className="success-actions" style={{ marginBottom: 24 }}><a className="button secondary small" href="#public-questions">{t("Browse public questions")}</a></div><div className="form-layout"><section className="form-panel">{done ? <Success title={t("Your voice has been heard.")}><p>{t("Your message is in the right inbox. Save the private receipt below to read your teacher’s answer.")}</p><div className="share-link">{receipt}</div><p className="field-help">{t("Anyone with this receipt can read your question and reply. We cannot recover it if you lose it.")}</p><div className="success-actions"><button className="button secondary" onClick={async () => { try { await navigator.clipboard.writeText(receipt); setCopied(true); } catch { setError("Copy the private link above manually."); } }}>{copied ? t("Link copied") : t("Copy receipt link")}</button><Link className="button primary" href={receipt}>{t("Read my answer")}</Link><button className="button secondary" onClick={() => { setDone(false); setBody(""); }}>{t("Ask another question")}<ArrowRight size={15} /></button></div><ErrorMessage message={error} /></Success> : <form onSubmit={submit}>
      <h2>{t("One question. A direct connection.")}</h2><p className="field-help" style={{ marginBottom: 26 }}>{t("Choose where your message goes. We’ll take it from there.")}</p>
      <ErrorMessage message={configError || error} />
      <fieldset style={{ border: 0, padding: 0, margin: "0 0 24px" }}><legend className="field-label">{t("Who would you like to reach?")}</legend><div className="segmented">{([
        ["teacher", "Specific teacher", GraduationCap], ["department", "Department", Users], ["general", "School life", School],
      ] as const).map(([value, label, Icon]) => <button type="button" key={value} className={`segment ${recipientType === value ? "selected" : ""}`} aria-pressed={recipientType === value} onClick={() => { setType(value); setId(""); }}><Icon size={15} />{t(label)}</button>)}</div></fieldset>
      {recipientType !== "general" && <label className="field"><span className="field-label">{recipientType === "teacher" ? t("Choose a teacher") : t("Choose a department")}</span><select className="input" required value={recipientId} onChange={e => setId(e.target.value)} disabled={loading || !!configError}><option value="">{loading ? t("Loading the school directory…") : t("Select a recipient")}</option>{recipientType === "teacher" ? config?.teachers.map(t => <option key={t.id} value={t.id}>{t.display_name}</option>) : config?.departments.map(d => <option key={d.id} value={d.id}>{t(d.name)}</option>)}</select>{recipientType === "teacher" && config && !config.teachers.length && <span className="field-help">{t("Your school hasn’t added its teachers yet. You can still write to a department or school life.")}</span>}</label>}
      <label className="field"><span className="field-label">{t("Your question or suggestion")}</span><textarea className="input" aria-label={t("Your question or suggestion")} placeholder={t("I’ve been wondering…")} required minLength={3} maxLength={280} value={body} onChange={e => setBody(e.target.value)} rows={6} /><span className="textarea-footer"><span>{t("A little kindness goes a long way.")}</span><span className={`counter ${body.length >= 270 ? "limit" : ""}`}>{body.length} / 280</span></span></label>
      <fieldset className="visibility-choice"><legend className="field-label">{t("Who can see your question?")}</legend><label className="visibility-option"><input type="radio" name="visibility" value="private" checked={visibility === "private"} onChange={() => setVisibility("private")} /><span><strong>{t("Private")}</strong><small>{t("Only authorized staff and anyone holding your receipt link. Teachers cannot publish it.")}</small></span></label><label className="visibility-option"><input type="radio" name="visibility" value="public" checked={visibility === "public"} onChange={() => setVisibility("public")} /><span><strong>{t("Public")}</strong><small>{t("Other students can see your anonymous question and the teacher’s answer.")}</small></span></label></fieldset>
      <label className="honeypot" aria-hidden="true">{t("Leave this empty")}<input name="website" autoComplete="off" tabIndex={-1} /></label>
      <div className="form-actions"><span className="privacy-note"><LockKeyhole size={14} /> {t("No name, email, or account attached.")}</span><SubmitButton pending={pending} disabled={loading || !!configError}>{t("Submit anonymously")}<ArrowRight size={16} /></SubmitButton></div>
    </form>}</section><aside className="info-panel"><ShieldCheck size={26} strokeWidth={1.5} /><h3>{t("Just your voice.")}<br />{t("Nothing attached.")}</h3><p>{t("Sometimes the best questions are the ones you’re a little hesitant to ask out loud.")}</p><div className="info-steps"><div className="info-step"><span className="info-number">01</span><div><strong>{t("Find the right inbox")}</strong><p>{t("A teacher, a department, or the wider school.")}</p></div></div><div className="info-step"><span className="info-number">02</span><div><strong>{t("Say what’s on your mind")}</strong><p>{t("Keep it thoughtful and under 280 characters.")}</p></div></div><div className="info-step"><span className="info-number">03</span><div><strong>{t("Let the conversation begin")}</strong><p>{t("Save your receipt to read the reply. Public questions can also appear on class boards.")}</p></div></div></div><div className="info-panel-foot"><MessageCircle size={14} style={{ verticalAlign: "middle", marginRight: 5 }} /> {t("You choose public or private. Both are anonymous. Please leave personal details out of your question.")}</div></aside></div>
    <section id="public-questions" style={{ marginTop: 40 }}><div className="section-heading"><h2>{t("Public questions")}</h2><span className="tag">{t("Anonymous voices")}</span></div><p className="field-help">{t("Questions shared publicly by students. Approved questions and their answers appear here.")}</p><ErrorMessage message={feedError} /><div className="question-list">{publicQuestions?.map(q => <article className="question-card" key={q.id}><span className="tag">{q.status === "answered" ? t("Answered") : t("Awaiting an answer")}</span><p>{q.body}</p>{q.answer && <div className="answer-block"><strong>{t("Teacher’s answer")}</strong><p>{q.answer}</p></div>}</article>)}</div>{publicQuestions?.length === 0 && <p>{t("No public questions yet. You can start the conversation.")}</p>}</section>
  </>;
}
